site_name: EUDI (Q)EAA Provider Technical Documentation
repo_url: https://github.com/nortal-lab/eudi-qeaa-doc

nav:
  - Summary: index.md
  - Versions: versions.md
  - Keywords: keywords.md
  - 1. Requirements and Scope: requirements.md
  - 2. Components: components.md
  - 3. Attestations:
      - 3.1. mDL: attestations/mdl.md
      - 3.2. PID: attestations/pid.md
      - 3.3. WIA: attestations/wia.md
  - 4. Flows:
      - 4.1. (Q)EAA Issuing: flows/qeaa-issuing.md
      - 4.2. (Q)EAA Presentation: flows/qeaa-presentation.md
  - 5. Endpoints:
      - 5.1. PAR Endpoint: endpoints/par.md
      - 5.2. Authorization Endpoint: endpoints/authorization.md
      - 5.3. Token Endpoint: endpoints/token.md
      - 5.4. Credential Endpoint: endpoints/credential.md
      - 5.5. Credential Nonce Endpoint: endpoints/credential-nonce.md
      - 5.6. Metadata Endpoints:
          - 5.6.1. Authorization Server: endpoints/metadata/as.md
          - 5.6.2. Credential Issuer: endpoints/metadata/credential-issuer.md
  - 6. Security Considerations: security-considerations.md

markdown_extensions:
  - codehilite
  - admonition
  - def_list
  - toc:
      permalink: "#"
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom

plugins:
  - search
  - mermaid2

hooks:
  - hooks/merge-content.py
  - hooks/append-reflinks.py

theme:
  name: material
  include_sidebar: false
  features:
    - navigation.expand
    - navigation.top

extra_css:
  - override.css

extra:
  font:
    code: 'Roboto Mono'
  palette:
    primary: 'Cyan'
    accent: 'Light Blue'
